#TargetName: Dependencies
#<TAB>commands

Build : project_main.c taxcalculator.c
	gcc project_main.c taxcalculator.c -o Taxcalculator.out

Run : Build
	./Taxcalculator.out

Clean : 
	rm -rf *.o *.out *.i *.s