name: Dynamic check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: 
         sudo apt-get -y install valgrind
    - name: Dynamic analysis
      run: make dynamic_analysis -C 3_Implementation
    
